server:
  port: 8081




spring:

  datasource:
    url: 'jdbc:postgresql://localhost:5432/chatapp'
    username: postgres
    password: damminhhai
    driver-class-name: org.postgresql.Driver
#     url: 'jdbc:mysql://localhost:3306/chatapp'
#     username: root
#     password:
#     driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    stomp:
      relay:
        host: localhost
        port: 61613
        login: guest
        passcode: guest

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 126264957196-hudervnfdsr05he83ei7g0kguo5thq31.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
#            redirect-uri: "localhost:8081/login/oauth2/code/google"
          github:
            client-id: Ov23liggGmJRWdWzMbBq
            client-secret: b5be760b41d988f4e729affb4aed4671e8837bc5
            scope: read:user, user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/github"

application:
  security:
    jwt:
      secret-key: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
      expiration: 86400000
      refresh-token:
        expiration: 604800000


#springdoc:
#  api-docs:
#    path: /api-docs          # Custom path for API documentation JSON
#  swagger-ui:
#    path: /swagger-ui        # Custom path for Swagger UI
#    operations-sorter: method  # Sort API operations by HTTP method
#    tags-sorter: alpha         # Sort API tags alphabetically
#    disable-swagger-default-url: true  # Disable default Swagger Petstore URL
#    doc-expansion: none       # Collapse all endpoints initially
#    display-request-duration: true  # Display the request duration
#  paths-to-match: /api/**     # Only include endpoints matching this path pattern
#  show-actuator: true

cloudinary:
  cloud-name: "dofftn6qy"
  api-key: "524579525171771"
  api-secret: "N_dM3WmsxxvIPxwzF2ra_qd1iXY"