server:
  port: 8081

spring:

  datasource:
    url: 'jdbc:postgresql://localhost:5432/chatapp'
    username: postgres
    password: damminhhai
    driver-class-name: org.postgresql.Driver
#     url: 'jdbc:mysql://localhost:3306/chatapp'
#     username: root
#     password:
#     driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    stomp:
      relay:
        host: localhost
        port: 61613
        login: guest
        passcode: guest


application:
  security:
    jwt:
      secret-key: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
      expiration: 86400000
      refresh-token:
        expiration: 604800000
